"""Practice: the gate in front of the card game, and the thumbs on a card.

The cards themselves are not served from here. They are static JSON on the
CDN, like the guides, so reading them costs nothing and works on a bad
connection. Two things still need the server.

`GET /practice` is the gate. Practice lives under Experiments, and the Terms
say the Experiments are not offered in states whose law restricts AI
delivered mental health support. Registering the route in
_EXPERIMENT_ROUTES is what applies that, the same way it applies to chat.
Like every geo control here it enforces a promise rather than containing
anything: the card files sit on a public CDN either way.

`POST /practice` records a thumb on a card. What is written is a count
against the card, with no identity attached at all. The token authorises the
call; it is not stored. So the table can say "nine people found this card
wrong" and can never say who found it wrong, which is why card feedback does
not appear in anyone's data export: none of it is theirs.
"""

import logging
import re

import storage
from responses import error, parse_body, respond

logger = logging.getLogger()

# Shown on the page and repeated here so the two cannot drift apart silently.
AI_NOTICE = (
    "The cards are generated by AI and can have mistakes."
)

VOTES = ("up", "down")
# Card ids are authored slugs (see tools/practice/rules.js). Anything else is
# either a bug or somebody poking at the table.
CARD_ID_RE = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")
MAX_CARD_ID = 80


def handle_practice_get(event: dict, user_id: str) -> dict:
    """Whether this person may play, and what the page has to tell them.

    The geo refusal happens in the router before this runs, so reaching here
    at all is the answer. There is nothing per person in the response.
    """
    return respond(200, {"ok": True, "notice": AI_NOTICE})


def handle_practice_vote(event: dict, user_id: str) -> dict:
    body = parse_body(event)

    card_id = body.get("card_id")
    if not isinstance(card_id, str) or len(card_id) > MAX_CARD_ID or not CARD_ID_RE.match(card_id):
        return error(400, "That is not a card.")

    vote = body.get("vote")
    if vote not in VOTES:
        return error(400, "A vote is up or down.")

    try:
        storage.consume_practice_quota(user_id)
    except storage.QuotaExceeded as exc:
        return error(429, str(exc))

    storage.record_card_vote(card_id, vote)
    # The subject is logged because every other route logs it and a support
    # question needs something to look at. The card is not logged beside it:
    # together they would rebuild exactly the per-person record this route
    # exists to avoid keeping.
    logger.info("Practice vote recorded for %s", user_id)
    return respond(200, {"ok": True})
