import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import awsService from './services/awsService';
import SiteNav from './components/SiteNav';
import Sprout from './components/Sprout';
import PracticeCard from './components/PracticeCard';
import PracticeExplain from './components/PracticeExplain';
import PracticeOptions from './components/PracticeOptions';
import PracticeSafetyStrip from './components/PracticeSafetyStrip';
import { usePageMeta } from './hooks/usePageMeta';
import { usePersistedState } from './hooks/usePersistedState';
import { useCardGesture } from './hooks/useCardGesture';
import { STORAGE_KEYS } from './utils/constants';
import {
  MAX_HISTORY,
  drawCard,
  loadManifest,
  loadPack,
  restCard,
  restIsDue,
} from './utils/deck';

/**
 * Practice: short cards on mental health concepts, two answers, a reason after
 * every one.
 *
 * Three things shape this page more than anything else.
 *
 * The surface does not scroll. That is what lets a scroll mean "next card"
 * without fighting the browser, and it is what keeps the whole card in view
 * without anyone having to look for the rest of it.
 *
 * The play surface carries no crisis line. That was a deliberate call on
 * 2026-09-18: the strip cost about a fifth of a phone screen on every card.
 * 988 is on the front card before anyone starts, on the summary, and inside
 * the feedback of any card marked sensitive, which is where it is actually
 * likely to be wanted. CLAUDE.md and PRE-DEPLOY.md were amended to match.
 *
 * The feed is a tape with a cursor rather than a stack. Up walks back through
 * what you have already seen, down walks forward through the same history,
 * and only at the head does down draw something new. So "down" means exactly
 * one thing everywhere, and going back to reread an explanation cannot lose
 * anyone's place.
 *
 * Nothing about an answer leaves this browser. What is kept is which
 * concepts someone has met and which cards they want to come back to, in
 * localStorage, cleared on sign out. There is no score anywhere, and there is
 * not going to be one: a percentage would be a made up number about somebody's
 * mental health, shown to a person who may be having a bad week.
 */

const EMPTY_PROGRESS = { seen: [], review: [], sessions: 0, lastSession: null };
const REVIEW_CAP = 12;

const AI_NOTICE = 'The cards are generated by AI and can have mistakes.';

// The movement hint, in the words of whatever is in the person's hand. It is
// the only thing left saying how to move, now that the buttons are gone, so
// it has to name the right gesture rather than a generic one.
const TOUCH_HINT = 'Tap or swipe left and right to answer. Swipe up for the next, down to go back.';
const KEY_HINT = 'A and D answer. S for the next card, W for the one before.';

// A card getting right answers should keep moving, but not before the
// explanation has been read: the explanation is the thing, and a card that
// slides away the moment you are right teaches nothing on the cards you get
// right. Any input cancels it, so staying longer is always possible.
const ADVANCE_MS = 3000;

const prefersReducedMotion = () =>
  typeof window !== 'undefined' &&
  window.matchMedia &&
  window.matchMedia('(prefers-reduced-motion: reduce)').matches;

/** True for a thumb, false for a mouse and keyboard. */
const isTouch = () =>
  typeof window !== 'undefined' &&
  window.matchMedia &&
  !window.matchMedia('(hover: hover) and (pointer: fine)').matches;

function PracticePage({ onSignOut }) {
  usePageMeta({
    title: 'Practice',
    description:
      'Short cards about mental health concepts, with two answers to choose between and an explanation after every one.',
    path: '/practice',
  });

  const [deck, setDeck] = useState(null);
  const [status, setStatus] = useState('loading');
  const [blocked, setBlocked] = useState('');
  const [progress, setProgress] = usePersistedState(STORAGE_KEYS.practice, EMPTY_PROGRESS);
  const [votes, setVotes] = usePersistedState(STORAGE_KEYS.practiceVotes, {});

  const [phase, setPhase] = useState('front');
  const [history, setHistory] = useState([]);
  const [cursor, setCursor] = useState(0);
  const [answered, setAnswered] = useState(0);
  const [allowSensitive, setAllowSensitive] = useState(true);
  const [note, setNote] = useState('');
  const [showKeys, setShowKeys] = useState(false);
  const [sessionMet, setSessionMet] = useState([]);

  const stackRef = useRef(null);
  const advanceTimer = useRef(null);
  const reduced = useMemo(prefersReducedMotion, []);
  const touch = useMemo(isTouch, []);

  useEffect(() => {
    let cancelled = false;
    (async () => {
      try {
        // The gate is the server's answer about where this request came
        // from. A refusal is legal and final. Anything else that goes wrong
        // with it is infrastructure, and infrastructure trouble should not
        // lock someone out of a page of flashcards, so only a 451 stops us.
        try {
          await awsService.practiceGate();
        } catch (err) {
          if (err.status === 451) {
            if (!cancelled) {
              setBlocked(err.message);
              setStatus('blocked');
            }
            return;
          }
        }

        const manifest = await loadManifest();
        const packs = await Promise.all(manifest.packs.map((pack) => loadPack(pack.file)));
        const pool = packs.flat();
        if (cancelled) return;
        if (!pool.length) throw new Error('no usable cards');
        setDeck({ manifest, pool });
        setStatus('ready');
      } catch (err) {
        if (!cancelled) setStatus('error');
      }
    })();
    return () => {
      cancelled = true;
    };
  }, []);

  const current = history[cursor] || null;
  const revealed = Boolean(current && (current.chosen || current.shown));
  const isRest = Boolean(current && current.card.kind === 'rest');

  /** Adds a card to the tape, trimming the far end so history stays bounded. */
  const push = useCallback((entry) => {
    setHistory((prev) => {
      const next = [...prev.slice(0, MAX_HISTORY - 1), entry];
      setCursor(next.length - 1);
      return next;
    });
  }, []);

  const drawNext = useCallback(() => {
    if (!deck) return;
    const card = drawCard(deck.pool, {
      history: history.map((entry) => entry.card),
      progress,
      allowSensitive,
    });
    if (!card) {
      setNote(
        `You have seen all ${deck.manifest.total_cards} cards. From here they come back around, ` +
          'starting with the ones you found hard.'
      );
      return;
    }
    push({
      card,
      chosen: null,
      shown: false,
      seenBefore: (progress.seen || []).includes(card.id),
    });
  }, [deck, history, progress, allowSensitive, push]);

  const advance = useCallback(() => {
    setNote('');
    if (cursor < history.length - 1) {
      setCursor(cursor + 1);
      return;
    }
    if (restIsDue(answered) && !isRest) {
      push({ card: restCard(answered), chosen: null, shown: false, seenBefore: false });
      return;
    }
    drawNext();
  }, [cursor, history.length, answered, isRest, push, drawNext]);

  const goBack = useCallback(() => {
    if (cursor > 0) {
      setNote('');
      setCursor(cursor - 1);
    } else {
      setNote('That is as far back as this goes.');
    }
  }, [cursor]);

  /**
   * Closing the explanation is what moves to the next card. Focus goes back
   * to the deck on the way out: the popup is about to unmount, and without
   * this the keyboard would be dead until somebody clicked something.
   */
  const dismissExplain = useCallback(() => {
    advance();
    if (stackRef.current) stackRef.current.focus();
  }, [advance]);

  /** Stops a pending auto-advance. Anything a person does calls this. */
  const cancelAdvance = useCallback(() => {
    if (advanceTimer.current) {
      clearTimeout(advanceTimer.current);
      advanceTimer.current = null;
    }
  }, []);

  /** Records that a card was met, and whether it is one to come back to. */
  const record = useCallback(
    (card, { comeBack }) => {
      setProgress((prev) => {
        const base = { ...EMPTY_PROGRESS, ...prev };
        const seen = base.seen.includes(card.id) ? base.seen : [...base.seen, card.id];
        let review = base.review.filter((id) => id !== card.id);
        if (comeBack) review = [...review, card.id].slice(-REVIEW_CAP);
        return { ...base, seen, review };
      });
      setSessionMet((prev) => (prev.includes(card.concept) ? prev : [...prev, card.concept]));
    },
    [setProgress]
  );

  const choose = useCallback(
    (side) => {
      if (!current || revealed) return;
      if (current.card.kind === 'rest') {
        if (side === 'left') setPhase('summary');
        else advance();
        return;
      }
      const picked = current.card.options.find((option) => option.side === side);
      const comeBack = Boolean(picked && picked.verdict === 'other');
      setHistory((prev) =>
        prev.map((entry, i) => (i === cursor ? { ...entry, chosen: side } : entry))
      );
      setAnswered((n) => n + 1);
      record(current.card, { comeBack });

      // A right answer keeps moving on its own. Only on a card that has a
      // right answer: on a "both" or a "support" card nobody is right, and
      // sliding the explanation away would be the whole point missed.
      if (picked && picked.verdict === 'taught') {
        cancelAdvance();
        advanceTimer.current = setTimeout(() => {
          advanceTimer.current = null;
          dismissExplain();
        }, ADVANCE_MS);
      }
    },
    [current, revealed, cursor, advance, record, cancelAdvance, dismissExplain]
  );

  const showMe = useCallback(() => {
    if (!current || revealed || isRest) return;
    setHistory((prev) => prev.map((entry, i) => (i === cursor ? { ...entry, shown: true } : entry)));
    setAnswered((n) => n + 1);
    // Met, but not got. Shown cards come back around.
    record(current.card, { comeBack: true });
  }, [current, revealed, isRest, cursor, record]);

  const skip = useCallback(() => {
    // One skip, and no heavy card appears again this session. No dialog and
    // no asking why: the feed can learn "not today" from a single tap.
    setAllowSensitive(false);
    setHistory((prev) => prev.filter((_, i) => i !== cursor));
    setCursor((c) => Math.max(0, c - 1));
    drawNext();
  }, [cursor, drawNext]);

  const retry = useCallback(() => {
    // Clears this attempt only. What was already recorded stands: a card you
    // got on the second go is still one to come back to.
    setHistory((prev) =>
      prev.map((entry, i) => (i === cursor ? { ...entry, chosen: null, shown: false } : entry))
    );
  }, [cursor]);

  const vote = useCallback(
    (value) => {
      if (!current) return;
      const id = current.card.id;
      setVotes((prev) => ({ ...prev, [id]: value }));
      // Sent and forgotten. If it does not arrive, the person still sees
      // their thumb and nothing about the card changes for them, so there is
      // nothing worth interrupting them about.
      awsService.votePracticeCard(id, value).catch(() => {});
    },
    [current, setVotes]
  );

  const start = useCallback(() => {
    setPhase('playing');
    setProgress((prev) => {
      const base = { ...EMPTY_PROGRESS, ...prev };
      return {
        ...base,
        sessions: (base.sessions || 0) + 1,
        lastSession: new Date().toISOString().slice(0, 10),
      };
    });
  }, [setProgress]);

  // The first card is drawn once the session starts and the deck is loaded.
  useEffect(() => {
    if (phase === 'playing' && deck && history.length === 0) drawNext();
  }, [phase, deck, history.length, drawNext]);

  const { bind, drag, attachWheel } = useCardGesture({
    onAnswer: choose,
    onNext: advance,
    onPrevious: goBack,
    canAnswer: Boolean(current) && !revealed,
    enabled: phase === 'playing',
    reducedMotion: reduced,
  });

  useEffect(() => attachWheel(stackRef.current), [attachWheel, phase]);

  useEffect(() => cancelAdvance, [cancelAdvance]);

  useEffect(() => {
    const onKey = (event) => {
      if (event.key === '?') setShowKeys((open) => !open);
      if (event.key === 'Escape') {
        setShowKeys(false);
        stackRef.current && stackRef.current.focus();
      }
    };
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, []);

  const shell = (children) => (
    <div className="flex flex-col min-h-screen h-full w-full paper-texture practice">
      <SiteNav signedIn onSignOut={onSignOut} />
      {children}
    </div>
  );

  if (status === 'loading') {
    return shell(
      <div className="practice-stage practice-stage--centred">
        <Sprout label="Loading the cards" />
      </div>
    );
  }

  if (status === 'blocked') {
    return shell(
      <div className="practice-stage practice-stage--centred">
        <div className="practice-message">
          <h1 className="practice-message__title">Not available where you are</h1>
          <p>{blocked}</p>
          <p>
            The guides are open to everyone and cover the same ground at more length.
          </p>
          <div className="practice-message__actions">
            <Link className="page-heading__action" to="/resources">
              Go to the guides
            </Link>
          </div>
        </div>
        <PracticeSafetyStrip />
      </div>
    );
  }

  if (status === 'error') {
    return shell(
      <div className="practice-stage practice-stage--centred">
        <div className="practice-message">
          <h1 className="practice-message__title">The cards are not loading right now.</h1>
          <p>The guides cover the same ground and they are still working.</p>
          <div className="practice-message__actions">
            <button type="button" className="page-heading__action" onClick={() => window.location.reload()}>
              Try again
            </button>
            <Link className="page-heading__action" to="/resources">
              Go to the guides
            </Link>
          </div>
        </div>
        <PracticeSafetyStrip />
      </div>
    );
  }

  const returning = (progress.sessions || 0) > 1 || (progress.seen || []).length > 0;

  if (phase === 'front') {
    return shell(
      <div className="practice-stage practice-stage--centred">
        <div className="practice-message">
          <p className="practice-meta__eyebrow">
            Practice <span className="practice-chip">beta</span>
          </p>
          <h1 className="practice-message__title">
            {returning ? 'Good to see you.' : 'Practice'}
          </h1>
          <p>
            Short cards about mental health concepts, with two answers to choose between and
            an explanation after every one.
          </p>
          <p className="practice-message__safety">
            These cards explain mental health concepts. They are not therapy, and none of the
            questions are about you. You can stop whenever you want. If you need to talk to
            someone now, call or text 988.
          </p>
          <p className="practice-message__ai">{AI_NOTICE}</p>
          <div className="practice-message__actions">
            <button type="button" className="practice-start" onClick={start}>
              {returning ? 'Keep going' : 'Start'}
            </button>
            <button type="button" className="practice-link" onClick={() => setShowKeys(true)}>
              How this works
            </button>
          </div>
          <p className="practice-message__hint">Tap an answer, or swipe it that way.</p>
        </div>
        {showKeys && <KeysSheet onClose={() => setShowKeys(false)} />}
        <PracticeSafetyStrip />
      </div>
    );
  }

  if (phase === 'summary') {
    // By label, not by concept id. Several concepts share a label (three of
    // them are "CBT"), and a list that reads "CBT, DBT, CBT, DBT, Sleep"
    // looks like a bug to the person reading it, because it is one.
    const newConcepts = [
      ...new Set(
        sessionMet
          .map((id) => deck.manifest.concepts.find((c) => c.id === id))
          .filter(Boolean)
          .map((c) => c.label)
      ),
    ];
    return shell(
      <div className="practice-stage practice-stage--centred">
        <div className="practice-message">
          <p className="practice-meta__eyebrow">This session</p>
          <h1 className="practice-message__title">
            {answered} {answered === 1 ? 'card' : 'cards'}.
          </h1>
          {newConcepts.length > 0 && (
            <p>You met {newConcepts.join(', ')}.</p>
          )}
          <div className="practice-message__actions">
            <Link className="page-heading__action" to="/resources">
              Read a guide
            </Link>
            <Link className="page-heading__action" to="/journal">
              Write about it
            </Link>
            <button type="button" className="practice-start" onClick={() => setPhase('playing')}>
              Keep going
            </button>
          </div>
          <p className="practice-message__ai">
            We do not save what you answered. Only which topics you have seen, and that stays
            in this browser.
          </p>
        </div>
        <PracticeSafetyStrip />
      </div>
    );
  }

  return shell(
    <section
      className="practice-stage"
      aria-labelledby="practice-title"
      // Anything a person does stops the card sliding out from under them.
      // The capture phase, so it lands before the action that caused it.
      onPointerDownCapture={cancelAdvance}
      onKeyDownCapture={cancelAdvance}
      onWheelCapture={cancelAdvance}
    >
      <h1 className="sr-only" id="practice-title">
        Practice
      </h1>

      <div className="practice-meta">
        <p className="practice-meta__eyebrow">
          Practice <span className="practice-chip">beta</span>
        </p>
        <p className="practice-meta__count">
          {note || (
            <button type="button" className="practice-link" onClick={() => setShowKeys(true)}>
              How this works
            </button>
          )}
        </p>
      </div>

      <p className="practice-ai">{AI_NOTICE}</p>

      <div
        className={`practice-stack ${drag.axis ? 'is-dragging' : ''}`}
        ref={stackRef}
        tabIndex={0}
        role="group"
        aria-label="Practice cards"
        {...bind}
        style={{
          transform: `translate(${drag.dx}px, ${drag.dy}px) rotate(${
            reduced || drag.axis !== 'x' ? 0 : Math.max(-7, Math.min(7, drag.dx * 0.04))
          }deg)`,
        }}
      >
        {current && (
          <PracticeCard
            card={current.card}
            revealed={revealed}
            seenBefore={current.seenBefore}
          />
        )}
      </div>
      <div className="practice-sliver" aria-hidden="true" />

      {current && (
        <PracticeOptions
          options={current.card.options}
          aiming={drag.aiming}
          committing={drag.committing}
          chosen={current.chosen}
          revealed={revealed}
          onChoose={choose}
          disabled={revealed}
        />
      )}

      <div className="practice-third">
        {!revealed && !isRest && current && current.card.sensitive ? (
          <button type="button" className="practice-link" onClick={skip}>
            Skip this one
          </button>
        ) : (
          !revealed &&
          !isRest && (
            <button type="button" className="practice-link" onClick={showMe}>
              Show me
            </button>
          )
        )}
      </div>

      <p className="practice-hint">{touch ? TOUCH_HINT : KEY_HINT}</p>

      {current && revealed && !isRest && (
        <PracticeExplain
          card={current.card}
          chosen={current.chosen}
          shown={current.shown}
          vote={votes[current.card.id]}
          onVote={vote}
          onRetry={retry}
          onDismiss={dismissExplain}
        />
      )}

      {showKeys && <KeysSheet onClose={() => setShowKeys(false)} />}
    </section>
  );
}

/** Five lines, never a wall, and it never opens on its own. */
function KeysSheet({ onClose }) {
  return (
    <div className="practice-keys" role="dialog" aria-label="How Practice works">
      <ul>
        <li>Swipe or click left and right to pick an answer. Or press A and D.</li>
        <li>Swipe up, scroll down, or press S for the next card.</li>
        <li>Swipe down, scroll up, or press W to go back to the card before.</li>
        <li>Show me gives you the explanation without guessing.</li>
        <li>
          The explanation floats over the card. Any move closes it and brings the next card:
          swipe, scroll, W, A, S, D, the arrows, Escape, or the button.
        </li>
        <li>There is no score, and what you answer is not saved anywhere.</li>
      </ul>
      <button type="button" className="page-heading__action" onClick={onClose}>
        Close
      </button>
    </div>
  );
}

export default PracticePage;
